# Generated by Django 2.2.1 on 2019-06-03 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
