# Generated by Django 2.2.1 on 2019-06-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20190603_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='update_at',
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
