# Generated by Django 2.2.1 on 2019-06-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20190611_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
