# Generated by Django 2.2.1 on 2019-06-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_remove_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
