# Generated by Django 2.2.1 on 2019-05-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_address',
            field=models.CharField(max_length=255),
        ),
    ]
