# Generated by Django 2.2.1 on 2019-06-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190613_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.TextField(blank=True),
        ),
    ]
