# Generated by Django 2.2.1 on 2019-06-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190625_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ship_address',
            field=models.TextField(),
        ),
    ]
